const dummy = [
  {
    date: "2021-09-20",
    kinds: "food",
    number: 1,
    price: "4000",
    spendContent: "저녁약속 (파스타)",
    spending: "18000",
  },
  {
    date: "2021-09-23",
    kinds: "shopping",
    number: 2,
    price: "38000",
    spendContent: "맨투맨 티셔츠",
    spending: "지출",
  },
  {
    date: "2021-09-28",
    kinds: "transportation",
    number: 3,
    price: "3200",
    spendContent: "지하철 (왕복)",
    spending: "지출",
  },
  {
    date: "2021-09-28",
    kinds: "coffee",
    number: 4,
    price: "4400",
    spendContent: "스타벅스 아아",
    spending: "지출",
  },
  {
    date: "2021-09-28",
    kinds: "date",
    number: 5,
    price: "44000",
    spendContent: "데이투♥",
    spending: "지출",
  },
  {
    date: "2021-10-02",
    kinds: "culture",
    number: 6,
    price: "12000",
    spendContent: "영화관 (혼영)",
    spending: "지출",
  },
  {
    date: "2021-10-09",
    kinds: "event",
    number: 7,
    price: "50000",
    spendContent: "결혼식 축의금",
    spending: "지출",
  },
  {
    date: "2021-10-14",
    kinds: "selfImprovement",
    number: 8,
    price: "32000",
    spendContent: "인프런 js 인강",
    spending: "지출",
  },
  {
    date: "2021-10-19",
    kinds: "exercise",
    number: 9,
    price: "150000",
    spendContent: "필라테스 한달 수강권",
    spending: "지출",
  },
  {
    date: "2021-10-23",
    kinds: "etc",
    number: 10,
    price: "1670000",
    spendContent: "월급",
    spending: "수입",
  },
  {
    date: "2021-11-01",
    kinds: "food",
    number: 11,
    price: "22000",
    spendContent: "삼겹살",
    spending: "지출",
  },
  {
    date: "2021-11-05",
    kinds: "coffee",
    number: 12,
    price: "14000",
    spendContent: "스벅 카페 쏜날",
    spending: "지출",
  },
  {
    date: "2021-11-05",
    kinds: "transportation",
    number: 13,
    price: "6400",
    spendContent: "약속 늦어서 택시",
    spending: "지출",
  },
  {
    date: "2021-11-10",
    kinds: "etc",
    number: 14,
    price: "100000",
    spendContent: "회사 보너스",
    spending: "수입",
  },
];

export const initialState = {
  user_name: JSON.parse(localStorage.getItem("userName")) || "testUser",
  money_list: JSON.parse(localStorage.getItem("money_list")) || dummy,
  edit_info: JSON.parse(localStorage.getItem("edit_info")) || null,
};
